### ISSUE TITLE
Need to port away from legacy PDB API (was: "Unable to load RSR analysis rsults file: `NoneType` object has no attribute `get`")

### ISSUE THREAD

**Issue by Sweetdragon115** [URVnutrigenomica-CTNS/VHELIBS#1]
I am running 3.0.9 and I keep getting this error when I run a single PDB code or a text file full of them like in the tutorial.

**Comment by ssorgatem** [comment]
That version is a bit ancient, can you try with the latest one (5.0)?
You can find it here:
https://130.206.36.133/owncloud/index.php/s/joaicjaOLPzPPtQ/download

**Comment by Sweetdragon115** [comment]
I get the error "Unable to load RSR analysis results file: HTTP Error 404: Not Found" when I run it with that version

**Comment by Sweetdragon115** [comment]
I'm still having this same error, I've tried on other computers and other networks but nothing is working. I get the error when I try to run anything, even PPARG_HUMAN like in the example

**Comment by ssorgatem** [comment]
Well, I've got bad news.
After looking into it, it looks like the API VHELIBS used to get quality data has been shut down:
http://www.rcsb.org/news?year=2020&article=5fc9176809ae2a096d081e28

It should be possible to port it to the new API, but I don't know when will I be able do do so.

**Comment by ssorgatem** [comment]
Fixed by 85e6d582f7bea23a4d8a2b1e6e03645745647f01
